// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package services

import (
	"github.com/baxiang/go-miro-practice/internal/app/reviews/repositories"
	"github.com/baxiang/go-miro-practice/internal/pkg/config"
	"github.com/baxiang/go-miro-practice/internal/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateReviewsService(cf string, sto repositories.ReviewsRepository) (ReviewsService, error) {
	viper, err := config.NewConfig(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	reviewsService := NewReviewService(logger, sto)
	return reviewsService, nil
}

// wire.go:

var ReviewsServiceProviderSet = wire.NewSet(config.ProviderSet, log.ProviderSet, ProviderSet)
