// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package controllers

import (
	"github.com/baxiang/go-miro-practice/internal/app/reviews/repositories"
	"github.com/baxiang/go-miro-practice/internal/app/reviews/services"
	"github.com/baxiang/go-miro-practice/internal/pkg/config"
	"github.com/baxiang/go-miro-practice/internal/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateReviewsController(cf string, sto repositories.ReviewsRepository) (*ReviewsController, error) {
	viper, err := config.NewConfig(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	reviewsService := services.NewReviewService(logger, sto)
	reviewsController := NewReviewsController(logger, reviewsService)
	return reviewsController, nil
}

// wire.go:

var ReviewControllerProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, services.ProviderSet, ProviderSet)
