// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package grpcservers

import (
	"github.com/baxiang/go-miro-practice/internal/app/reviews/services"
	"github.com/baxiang/go-miro-practice/internal/pkg/config"
	"github.com/baxiang/go-miro-practice/internal/pkg/log"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateReviewsServer(cf string, service services.ReviewsService) (*ReviewsServer, error) {
	viper, err := config.NewConfig(cf)
	if err != nil {
		return nil, err
	}
	options, err := log.NewOptions(viper)
	if err != nil {
		return nil, err
	}
	logger, err := log.NewLogger(options)
	if err != nil {
		return nil, err
	}
	reviewsServer, err := NewReviewsServer(logger, service)
	if err != nil {
		return nil, err
	}
	return reviewsServer, nil
}

// wire.go:

var grpcReviewsProviderSet = wire.NewSet(log.ProviderSet, config.ProviderSet, ProviderSet)
